model:
  arch: pointvlm

  # vision encoder
  vision_model: "point_transformer"
  drop_path_rate: 0
  use_grad_checkpoint: False
  precision: "fp16"
  freeze_vision: True

  # generation configs
  prompt: ""

  language_model: "meta-llama/Llama-2-7b-chat-hf"
  lora_r: 64
  lora_alpha: 16


preprocess:
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"