model:
  arch: pointvlm
  model_type: pretrain
  max_txt_len: 1024
  image_size: 224
  end_sym: "</s>"
  vision_model: "point_transformer"
  language_model: "meta-llama/Llama-2-7b-chat-hf"
  ckpt: "checkpoint"
  use_grad_checkpoint: True
  chat_template: True
  freeze_vision: False
  low_resource: True
  lora_r: 64
  lora_alpha: 16
  bits: 8

datasets:
  pointvlm_train:
    batch_size: 4
    num_points: 200000
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 3
  num_workers: 2
  warmup_steps: 1000
  iters_per_epoch: 3750

  seed: 42
  output_dir: "checkpoint"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: False

  wandb_log: True
  wandb_token: "ebc667f949a72cc90bd5fd1546629e1e8d677487"
  job_name: pointllm_finetune_scannet